### ISSUE TITLE
css not loading

### ISSUE THREAD

**Issue by meghakundu** [ardinur03/PrakerinKuy#1]
Please help with this @ardinur03 
![image](https://github.com/user-attachments/assets/79fee65e-9501-4726-979c-020fe86d0a76)

**Comment by ardinur03** [comment]
Please check the file at the path **_PrakerinKuy-main\resources\views\welcome.blade.php_** and remove _CSS_, or _JavaScript_ tags that contain the **_integrity_** and **_rossorigin_** attributes. Happy coding!

**Comment by meghakundu** [comment]
It works.
