### ISSUE TITLE
Few tables missing in db

### ISSUE THREAD

**Issue by meghakundu** [ardinur03/PrakerinKuy#2]
'siswa','jurusan','pengajuansiswa','perusahaan'. These models are present in folder structure but not in db, also their respective data are missing. @ardinur03 May you help with this too, unable to go through dashboard.

**Comment by ardinur03** [comment]
![image](https://github.com/user-attachments/assets/693e139c-0a98-413d-a42e-82842634438d)
I have uploaded the database file, you just need to import the database. Good luck 👋

**Comment by meghakundu** [comment]
> ![image](https://private-user-images.githubusercontent.com/60333726/355702282-693e139c-0a98-413d-a42e-82842634438d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODg1NTIsIm5iZiI6MTcyMzA4ODI1MiwicGF0aCI6Ii82MDMzMzcyNi8zNTU3MDIyODItNjkzZTEzOWMtMGE5OC00MTNkLWE0MmUtODI4NDI2MzQ0MzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMzczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMTczOGRjMjZjMmM0NDZhMDg3ZTcwNDJhM2ZkNTg3N2I1NmIyMjI4NDRmMjQwMWYzNGVhMzFmYTk3NDc4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XBnz5PCEjWHl5c6CKSE2rOgEykPP3qF1u19TmiLahUY) I have uploaded the database file, you just need to import the database. Good luck 👋

thanks :)
